### PR TITLE
Multiple output grids

### LINKED ISSUE #481: Multiple output grids
## Description
fv3atm should support outputting history files for parent and all nested domains 

## Solution
Update fv3 cap and write grid component to enable more than one set of history files to be written out.

## Alternatives
Use FMS diag manager to write out outputs on all nested domains.

## Testing:

1. Have you tested the code changes? Yes On what platforms? Hera.
2. Have you run regression test in ufs-weather-model or ufs-s2s-model with code changes? Yes/
- Will the baseline results change? Yes.
- If yes, please give brief explanation of your code updates on the regression test. Nested HAFS tests will now have history files written for each domain.

## Dependent PRs:

Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- required to support noaa-emc/GFDL_atmos_cubed_sphere/issues/<issue_number>
- ncar/ccpp-physics/pull/<pr_number>
- associated ufs-weather-model/pull/<pr_number>

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**
## Description

Update fv3 cap and write grid component to enable outputting multiple domains. This is done be creating an array of fcstGrids, and array of rout handles where each element of these arrays correspond to one atm domain. In the write grid component updates were made to allow grid spec parameters for each output grid to be specified separately. 

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues should always be created before starting work on a PR branch!)
- fixes https://github.com/NOAA-EMC/fv3atm/issues/481

## Testing

How were these changes tested?  ufs regression test on hera
What compilers / HPCs was it tested with?  Intel.
Are the changes covered by regression tests? Yes.
Have the ufs-weather-model regression test been run? Yes. On what platform? Hera.  
- Will the code updates change regression test baseline? Yes. All multiple domain HAFS tests have new history outputs. And outputs of all global single domain tests will be chaged do to slight difference in how fcstGrid is now defined.
- Please commit the regression test log files in your ufs-weather-model branch

## Dependencies

If testing this branch requires non-default branches in other repositories, list them.
Those branches should have matching names (ideally)

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/176

### CODE REVIEW

File: module_fcst_grid_comp.F90 [hunk 1]
```diff
@@ -133,6 +137,173 @@ end subroutine SetServices
 !-----------------------------------------------------------------------
 !#######################################################################
 !-----------------------------------------------------------------------
+!
+  subroutine SetServicesNest(nest, rc)
```
Comment (theurich) [inline module_fcst_grid_comp.F90:141]: I thought you wanted to rename SetSerivcesNest() to something without the word "Nest"? E.g. SetServicesDomain()? Then also rename the variable "nest" to "domain"? It will complicate Dan's merge. But if we don't do it now, it will probably stay the way it is.

File: module_fcst_grid_comp.F90 [hunk 2]
```diff
@@ -455,157 +631,101 @@ subroutine fcst_initialize(fcst_comp, importState, exportState, clock, rc)
...
-          ! do the actual broadcast of the petMap
-          call ESMF_VMBroadcast(vm, bcstData=petMap, count=peListSize(1), rootPet=nestRootPet, rc=rc)
-          if (ESMF_LogFoundError(rcToCheck=rc, msg=ESMF_LOGERR_PASSTHRU, line=__LINE__, file=__FILE__)) return
+          call ESMF_GridAddCoord(fcstGrid(n), staggerLoc=ESMF_STAGGERLOC_CENTER, rc=rc); ESMF_ERR_ABORT(rc)
+          call ESMF_GridAddCoord(fcstGrid(n), staggerLoc=ESMF_STAGGERLOC_CORNER, rc=rc); ESMF_ERR_ABORT(rc)
 
-          ! create the DELayout that maps DEs to the PETs in the petMap
-          delayout = ESMF_DELayoutCreate(petMap=petMap, rc=rc)
-          if (ESMF_LogFoundError(rcToCheck=rc, msg=ESMF_LOGERR_PASSTHRU, line=__LINE__, file=__FILE__)) return
+          ! define "center" coordinate values
```
Comment (theurich) [inline module_fcst_grid_comp.F90:703]: It seems cleaner to stay with radians, and not to convert to degrees. As discussed previously, and shown by Dusan's test runs, we already are seeing bit-for-bit changes due to changing over to the FCST coords (instead of reading from file for global). Might as well deal with bit changes once, remove dtor variable and be done with it.

File: fv3_cap.F90 [hunk 3]
```diff
@@ -1185,6 +1157,9 @@ subroutine ModelFinalize(gcomp, rc)
       enddo
     endif
 
+    call ESMF_VMBarrier(vm=vm, rc=rc)
```
Comment (theurich) [inline fv3_cap.F90]: I don't think this Barrier() is needed, and should not be added.

**Review by theurich — CHANGES_REQUESTED** [review]
Left 3 comments to look at.

File: module_fcst_grid_comp.F90 (hunk 2 above)
Comment (theurich) [reply module_fcst_grid_comp.F90:703]: This is obviously the wrong section of the code showing up in the comment. I had highlighted where the conversions are being computed, filling in the coord values.

File: module_fcst_grid_comp.F90 (hunk 1 above)
Comment (DusanJovic-NOAA) [reply module_fcst_grid_comp.F90:141]: Let's remember to rename this routine in the following PR (Dan will be updating this routine in his PR anyway).

File: module_fcst_grid_comp.F90 (hunk 2 above)
Comment (DusanJovic-NOAA) [reply module_fcst_grid_comp.F90:703]: I decided to leave the values in degrees, because that's the default and even if we change the code here, we'll need to do the conversion from rad to deg in write_netcdf and probably in other output routines, so maybe it's better to just do the conversion once, at the time grids are defined.

File: fv3_cap.F90 (hunk 3 above)
Comment (DusanJovic-NOAA) [reply fv3_cap.F90]: Removed in 48768632629a583b5b55ca0239493da655ec7a5a

**Comment by BinLiu-NOAA** [comment]
@DusanJovic-NOAA or @junwang-noaa, Just for clarification, will inline post work for multiple output grids with this PR, or that will require future development or code changes? Thanks!

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA or @junwang-noaa, Just for clarification, will inline post work for multiple output grids with this PR, or that will require future development or code changes? Thanks!

If nested regression tests are not using inline post, then I don't know.

**Comment by BinLiu-NOAA** [comment]
> > @DusanJovic-NOAA or @junwang-noaa, Just for clarification, will inline post work for multiple output grids with this PR, or that will require future development or code changes? Thanks!
> 
> If nested regression tests are not using inline post, then I don't know.

Thanks @DusanJovic-NOAA! We will test the inline post capability for the nesting configurations after this PR goes in. In the future, we can either change some of existing nesting RTs (preferred) or add a nesting RT to test multiple output with inline post. Thanks!

**Review by BinLiu-NOAA — APPROVED** [review]
Changes look good to me. Thanks for this series of development to enable outputting both parent and nested grids!

**Comment by junwang-noaa** [comment]
@theurich Are the code changes looking good to you?

File: module_fcst_grid_comp.F90 (hunk 1 above)
Comment (theurich) [reply module_fcst_grid_comp.F90:141]: FYI for @danrosen25.

File: module_fcst_grid_comp.F90 (hunk 2 above)
Comment (theurich) [reply module_fcst_grid_comp.F90:703]: @junwang-noaa what do you think? Personally I much rather see the ESMF fcstGrid defined **exactly** as the model uses it, No conversion at all. We have ESMF grid as R8, so we can capture FV3's geometry arrays precisely, no matter how FV3 is compiled. I understand that the fcstGrid is in degrees, and that is fine, it just stays that way. ESMF will do the regridding either way. Less convenversions on the user level just seems clearer. And since we have bit changes no matter what, we might as well do it as clean in the PR as we can.

File: module_fcst_grid_comp.F90 [hunk 4]
```diff
@@ -455,157 +631,102 @@ subroutine fcst_initialize(fcst_comp, importState, exportState, clock, rc)
...
+             petListNest(k-pelist(1)+1) = k
+             k = k + 1
+          end do
+          end do
 
-          if (mype == 0) TileLayout = Atmos%layout
-          call ESMF_VMBroadcast(vm, bcstData=TileLayout, count=2, &
-                                  rootPet=0, rc=rc)
-          if (ESMF_LogFoundError(rcToCheck=rc, msg=ESMF_LOGERR_PASSTHRU, line=__LINE__, file=__FILE__)) return
+          fcstGridComp(n) = ESMF_GridCompCreate(name="nest", petList=petListNest, rc=rc); ESMF_ERR_ABORT(rc)
```
Comment (junwang-noaa) [inline module_fcst_grid_comp.F90:681]: @danrosen25 Please see Gerhard's comment above, if you rename the SetServicesNest, maybe rename the name here too as it contains regional top domain too.

File: module_fcst_grid_comp.F90 (hunk 2 above)
Comment (junwang-noaa) [reply module_fcst_grid_comp.F90:703]: I want to confirm that we are talking about line 706, 711,717 and 722. I think it' good to keep the coordinates same as the model especially those grids are also used in other places such as coupling. We may also need to write out the coordinates in radians not in degrees for consistency in netcdf files.  We can make the changes in next PR.

Comment (theurich) [reply module_fcst_grid_comp.F90:703]: So remove the conversion here, and get rid of the 'dtor' variable in this PR. Then deal with output changes you mention in a future PR.

Comment (DusanJovic-NOAA) [reply module_fcst_grid_comp.F90:703]: If we remove conversion here, conversion from rad to deg must be added to module_write_netcdf, and somewhere in ioCompRun or ESMFproto_FieldBundleWrite.

Comment (junwang-noaa) [reply module_fcst_grid_comp.F90:703]: Since this PR does not change model output results except adding multiple domain output files for HAFS tests. I think it's better we keep the code changes in this PR and have a separate PR with radian coordinates for both forecast grids, write grids and coordinates in output files .

Comment (theurich) [reply module_fcst_grid_comp.F90:703]: @junwang-noaa : this PR **does** change model output results for global domain. @DusanJovic-NOAA can confirm or correct.

Comment (DusanJovic-NOAA) [reply module_fcst_grid_comp.F90:703]: See a5d9ebe

File: fv3_cap.F90 [hunk 5]
```diff
@@ -218,7 +216,7 @@ subroutine InitializeAdvertise(gcomp, rc)
     call NUOPC_ModelGet(gcomp, driverClock=clock, importState=importState, exportState=exportState, rc=rc)
     if (ESMF_LogFoundError(rcToCheck=rc, msg=ESMF_LOGERR_PASSTHRU, line=__LINE__, file=__FILE__)) return
 
-    call ESMF_AttributeGet(gcomp, name="ProfileMemory", value=value, defaultValue="true", &
+    call ESMF_AttributeGet(gcomp, name="ProfileMemory", value=value, defaultValue="false", &
```
Comment (junwang-noaa) [inline fv3_cap.F90:219]: Can we still have "ProfileMemory" to be true?

File: module_fcst_grid_comp.F90 (hunk 2 above)
Comment (junwang-noaa) [reply module_fcst_grid_comp.F90:703]: @theurich That is correct, thanks. Dusan made the code changes, please review again. Thanks

File: fv3_cap.F90 (hunk 5 above)
Comment (theurich) [reply fv3_cap.F90:219]: You can turn this on at run-time, in the nems.configure, by setting ProfileMemory=.true. under the ATM attributes. I think the default should be "false" in the code to reduce the noise, and if you want it on, just set it in the nems.configure. Does that make sense?

File: module_fcst_grid_comp.F90 (hunk 2 above)
Comment (theurich) [reply module_fcst_grid_comp.F90:703]: That looks good to me now. Thank you!

File: fv3_cap.F90 (hunk 5 above)
Comment (junwang-noaa) [reply fv3_cap.F90:219]: I see, thanks.

**Review by theurich — APPROVED** [review]
This PR now looks good to me.

**Review by junwang-noaa — APPROVED** [review]

File: io/inline_post.F90 [hunk 6]
```diff
@@ -16,7 +16,7 @@ module inline_post
 
   contains
 
-  subroutine inline_post_run(wrt_int_state,mypei,mpicomp,lead_write,      &
+  subroutine inline_post_run(wrt_int_state,grid_id,mypei,mpicomp,lead_write,      &
```
Comment (MicroTed) [inline io/inline_post.F90:19]: This change needed in the inline_post_stub.F90 as well

File: io/inline_post.F90 [hunk 7]
```diff
@@ -55,21 +56,22 @@ end subroutine inline_post_run
 !
 !-----------------------------------------------------------------------
 !
-    subroutine inline_post_getattr(wrt_int_state)
+    subroutine inline_post_getattr(wrt_int_state,grid_id)
```
Comment (MicroTed) [inline io/inline_post.F90:59]: This change needed in the inline_post_stub.F90 as well
