### PR TITLE
fix initialization issue for moving nest grid in debug mode

### LINKED ISSUE #1588: hafs_regional_storm_following_1nest_atm_ocn failed with debug test
## Description
Hafs group reported that the hafs_regional_storm_following_1nest_atm_ocn test failed in debug mode. The error showed in the moving nest lat info in the module_wrt_grid_comp.F90. 

### To Reproduce:
From Biju:
I ran regression tests with "hafs_regional_storm_following_1nest_atm_ocn_wav" and "hafs_regional_storm_following_1nest_atm_ocn" with DEBUG flag on.

The first one (hafs_regional_storm_following_1nest_atm_ocn_wav) completed successfully, but the second one(hafs_regional_storm_following_1nest_atm_ocn) failed with the error: 

forrtl: error (72): floating overflow
Image              PC                Routine            Line        Source
fv3.exe            000000000FDCDAAB  Unknown               Unknown  Unknown
libpthread-2.31.s  000014EB7A0AF8C0  Unknown               Unknown  Unknown
fv3.exe            0000000005C1454B  module_wrt_grid_c         759  module_wrt_grid_comp.F90

One difference I noticed between these two runs is that in the first one, the output_grid is (rotated_latlon,rotated_latlon), while in the second one, the output_grid is (regional_latlon, regional_latlon_moving).

### PR DESCRIPTION
**Pull request by junwang-noaa**
## Description

Hafs group reported that the hafs_regional_storm_following_1nest_atm_ocn test failed in debug mode. The error showed in the moving nest lat info in the module_wrt_grid_comp.F90.

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues should always be created before starting work on a PR branch!)
- fixes https://github.com/ufs-community/ufs-weather-model/issues/1588

## Testing

How were these changes tested?  
Tested on hera with the hafs_regional_storm_following_1nest_atm_ocn test using executable compiled with DEBUG option.

What compilers / HPCs was it tested with?  
Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)  
Have the ufs-weather-model regression test been run? On what platform?  
- Will the code updates change regression test baseline? If yes, why? Please show the baseline directory below.
- Please commit the regression test log files in your ufs-weather-model branch

## Dependencies

If testing this branch requires non-default branches in other repositories, list them.
Those branches should have matching names (ideally)

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- UFS WM https://github.com/ufs-community/ufs-weather-model/pull/1606

### CODE REVIEW

**Review by DusanJovic-NOAA — APPROVED** [review]

File: io/module_wrt_grid_comp.F90 [hunk 1]
```diff
@@ -754,12 +754,14 @@ subroutine wrt_initialize_p1(wrt_comp, imp_state_write, exp_state_write, clock,
...
-              wrt_int_state%out_grid_info(n)%latPtr(i,j) = latPtr(i,j)
-              wrt_int_state%out_grid_info(n)%lonPtr(i,j) = lonPtr(i,j)
-          enddo
-          enddo
+          if ( trim(output_grid(n)) /= 'regional_latlon_moving' .and. trim(output_grid(n)) /= 'rotated_latlon_moving' ) then
+            do j=wrt_int_state%out_grid_info(n)%j_start, wrt_int_state%out_grid_info(n)%j_end
+            do i=wrt_int_state%out_grid_info(n)%i_start, wrt_int_state%out_grid_info(n)%i_end
+                wrt_int_state%out_grid_info(n)%latPtr(i,j) = latPtr(i,j)
+                wrt_int_state%out_grid_info(n)%lonPtr(i,j) = lonPtr(i,j)
+            enddo
```
Comment (BrianCurtis-NOAA) [inline io/module_wrt_grid_comp.F90:762]: It's a common practice to indent nested do loops.

**Review by BrianCurtis-NOAA — APPROVED** [review]

File: io/module_wrt_grid_comp.F90 (hunk 1 above)
Comment (junwang-noaa) [reply io/module_wrt_grid_comp.F90:762]: Done
