### PR TITLE
Fix stochastic physics restart runs, remove rayleigh damping from all suite definition files

### LINKED ISSUE #340: Remove scheme `rayleigh_damp` from all suite definition files
## Description

Rayleigh damping in physics isn't used with fv3atm, because the dycore handles it. The CCPP scheme `rayleigh_damp` returns immediately if certain conditions are met, and these are true for all ufs-weather-model runs:
```
if (lsidea .or. ral_ts <= 0.0 .or. prslrd0 == 0.0) return
```

PR https://github.com/NOAA-EMC/fv3atm/pull/303 removes `rayleigh_damp` from a handful of suite definition files. We should remove it from all other suite definitin files, too.

### PR DESCRIPTION
**Pull request by climbfuji**
## Description

This PR combines two changes:
- A fix in `stochastic_physics/stochastic_physics_wrapper.F90` for reproducible restart runs, contributed by @lisa-bengtsson (see https://github.com/ufs-community/ufs-weather-model/discussions/737 for more information)
- Removal of scheme `rayleigh_damp` from all remaining suite definition files in `ccpp/suites/`

### Issue(s) addressed

Fixes https://github.com/NOAA-EMC/fv3atm/issues/340.

## Testing

See https://github.com/ufs-community/ufs-weather-model/pull/751.

### CODE REVIEW

File: stochastic_physics/stochastic_physics_wrapper.F90 [hunk 1]
```diff
@@ -294,9 +294,7 @@ subroutine stochastic_physics_wrapper (GFS_Control, GFS_Data, Atm_block, ierr)
          endif ! lndp block
       end if
 
-    endif initalize_stochastic_physics
-
-    if (GFS_Control%do_ca .and. is_initialized) then
+    if (GFS_Control%do_ca) then
```
Comment (SMoorthi-emc) [inline stochastic_physics/stochastic_physics_wrapper.F90]: I suggest aligning this if block and the code underneath by shifting 2 spaces t the right.

**Review by SMoorthi-emc — APPROVED** [review]

File: stochastic_physics/stochastic_physics_wrapper.F90 (hunk 1 above)
Comment (junwang-noaa) [reply stochastic_physics/stochastic_physics_wrapper.F90]: agree

Comment (climbfuji) [reply stochastic_physics/stochastic_physics_wrapper.F90]: Agree as well. @lisa-bengtsson I'll do as @SMoorthi-emc suggested.

Comment (climbfuji) [reply stochastic_physics/stochastic_physics_wrapper.F90]: Done,  also aligned the `endif` so that the indentation matches.

**Review by DeniseWorthen — APPROVED** [review]

**Comment by climbfuji** [comment]
@junwang-noaa I fixed the indentation, and all regression tests passed. Please review and approve if satisfied. Thanks!

**Review by junwang-noaa — APPROVED** [review]
