### PR TITLE
Consider surface ocean current in air-sea flux calculation

### LINKED ISSUE #753: Consider surface ocean current in the computation of air-sea fluxes
## Description
The surface layer scheme will be updated to include surface ocean current in the computation of air-sea fluxes.

## Solution
The ccpp-physics, GFDL_atmos_cubed_sphere and fv3atm will be updated.

## Alternatives
If applicable, add a description of any alternative solutions or features you've considered.

## Testing:

1. Have you tested the code changes? On what platforms? Yes, on Hera
2. Have you run regression test in ufs-weather-model or ufs-s2s-model with code changes?
- Will the baseline results change? The baseline results will not change.
- If yes, please give brief explanation of your code updates on the regression test.

## Dependent PRs:

Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/311
https://github.com/ufs-community/ccpp-physics/pull/155

### LINKED ISSUE #1975: Enable taking into account sea surface current in atmosphere-ocean coupling
## Description

Currently, sea surface current (SSC) is not considered in ufs-weather-model atmosphere-ocean coupling. We would like to take into account the SSC impact on air-sea momentum and enthalpy flux calculations by using the SSC-relative winds.

## Solution

Passing SSC from ocean model component (e.g., MOM6) through CMEPS into FV3ATM, and within FV3ATM (and ccpp-physics) taking into consideration SSC when calculating air-sea momentum and enthalpy fluxes. Currently some HAFS developers (e.g., @binli2337) is working to enable this capability for the UFS HAFS application.

## Alternatives

Do not consider SSC impacts on atmosphere-ocean coupling.

## Related to

- fixed by ufs-community/ufs-weather-model/pull/2104
- fixed by NOAA-EMC/fv3atm/pull/755
- fixed by NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/311
- fixed by ufs-community/ccpp-physics/pull/155
- fixed by NOAA-EMC/CMEPS/pull/107

### PR DESCRIPTION
**Pull request by binli2337**
## Description

This PR will update ccpp-physics and GFDL_atmos_cubed_sphere components to include surface ocean current in the computation of air-sea fluxes. 

This PR will also add a new namelist called "icplocn2atm."
When icplocn2atm=0, surface ocean current is not used in the computation of air-sea fluxes.
When icpocn2atm=1, surface ocean current is used in the computation of air-sea fluxes.

### Issue(s) addressed
- fixes #753 
- fixes ufs-community/ufs-weather-model/issues/1975

## Testing

How were these changes tested?  The changes were tested in the HAFS-MOM6 system.
What compilers / HPCs was it tested with?  Intel
Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)
New tests will not be added to UFS regression test system.
Have the ufs-weather-model regression test been run? On what platform?  Yes, on Hera.
- Will the code updates change regression test baseline? If yes, why? Please show the baseline directory below. No
- Please commit the regression test log files in your ufs-weather-model branch

## Dependencies

If testing this branch requires non-default branches in other repositories, list them.
Those branches should have matching names (ideally)

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on ufs-community/ccpp-physics/pull/155
- waiting on NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/311
- related to NOAA-EMC/CMEPS/pull/107
- needed by ufs-community/ufs-weather-model/pull/2104

Co-authored-by: @binli2337, @BinLiu-NOAA, @WeiguoWang-NOAA, @BijuThomas-NOAA, @hyunsookkim-NOAA, @XuLi-NOAA, @MariaAristizabal-NOAA, @JohnSteffen-NOAA

### CODE REVIEW

File: atmos_model.F90 [hunk 1]
```diff
@@ -1977,6 +1977,58 @@ subroutine assign_importdata(jdat, rc)
             endif
           endif
 
+! get zonal ocean current:
+!--------------------------------------------------------------------------
+          fldname = 'ocn_current_zonal'
+          if (trim(impfield_name) == trim(fldname)) then
+            findex  = queryImportFields(fldname)
+            if (importFieldsValid(findex) .and. GFS_control%cplocn2atm) then
```
Comment (DeniseWorthen) [inline atmos_model.F90:1985]: To confirm....cplocn2atm is always true for the global configurations. When the ufs fields exchange is used for mom6 regional, these fields will now be available and connected for the global configuration. But they still will not be used, because the ``icplocn2atm`` can still be 0.  Is that correct?

Comment (binli2337) [reply atmos_model.F90:1985]: @DeniseWorthen The default value for icplocn2atm is 0. To use this parameter, it is necessary to add icplocn2atm = 1 in input.nml.

**Review by DeniseWorthen — APPROVED** [review]
The changes look OK to me, but someone w/ more familiarity w/ the moving nest code should also review.

File: ccpp/suites_not_used/suite_FV3_HAFS_v1_thompson_noahmp_nonsst.xml [hunk 2]
```diff
@@ -18,7 +18,6 @@
       <scheme>rad_sw_pre</scheme>
```
Comment (junwang-noaa) [inline ccpp/suites_not_used/suite_FV3_HAFS_v1_thompson_noahmp_nonsst.xml:18]: There is a plan to delete the suites under suites_not_used, is this xml still used in HAFS experiments?

File: ccpp/suites_not_used/suite_FV3_HAFS_v1_thompson_noahmp.xml [hunk 3]
```diff
@@ -18,7 +18,6 @@
       <scheme>rad_sw_pre</scheme>
```
Comment (junwang-noaa) [inline ccpp/suites_not_used/suite_FV3_HAFS_v1_thompson_noahmp.xml:18]: See comments below.

File: ccpp/suites_not_used/suite_FV3_HAFS_v1_thompson_noahmp_nonsst.xml (hunk 2 above)
Comment (BinLiu-NOAA) [reply ccpp/suites_not_used/suite_FV3_HAFS_v1_thompson_noahmp_nonsst.xml:18]: @junwang-noaa the suite_FV3_HAFS_v1_thompson_noahmp_nonsst.xml and suite_FV3_HAFS_v1_thompson_noahmp.xml are most likely needed in 2024 HAFS real-time parallel experiment configurations. In this case, not sure what to do, shall we move them out from the suites_not_used dir now?

Comment (BinLiu-NOAA) [reply ccpp/suites_not_used/suite_FV3_HAFS_v1_thompson_noahmp_nonsst.xml:18]: In any case, we will keep a note, probably move them out in a future PR, before them being deleted. Thanks!

**Review by BinLiu-NOAA — APPROVED** [review]
Looks good. Tested under HAFS application already.

File: ccpp/suites_not_used/suite_FV3_HAFS_v1_thompson_noahmp_nonsst.xml (hunk 2 above)
Comment (junwang-noaa) [reply ccpp/suites_not_used/suite_FV3_HAFS_v1_thompson_noahmp_nonsst.xml:18]: Yes, I suggest moving them out from the "suites_not_used" in the next fv3 PR. Thanks

**Review by junwang-noaa — APPROVED** [review]

**Comment by grantfirl** [comment]
https://github.com/ufs-community/ccpp-physics/pull/155 was merged. This PR branch is ready to revert .gitmodules and commit the latest ufs/dev hash of ccpp-physics: https://github.com/ufs-community/ccpp-physics/commit/51452b8b52d5f3ded391847aefc21b086bb27b64

File: ccpp/suites_not_used/suite_FV3_HAFS_v1_thompson_noahmp.xml (hunk 3 above)
Comment (BinLiu-NOAA) [reply ccpp/suites_not_used/suite_FV3_HAFS_v1_thompson_noahmp.xml:18]: Same response as above. Will move it out in a future PR.

**Comment by BinLiu-NOAA** [comment]
> [ufs-community/ccpp-physics#155](https://github.com/ufs-community/ccpp-physics/pull/155) was merged. This PR branch is ready to revert .gitmodules and commit the latest ufs/dev hash of ccpp-physics: [ufs-community/ccpp-physics@51452b8](https://github.com/ufs-community/ccpp-physics/commit/51452b8b52d5f3ded391847aefc21b086bb27b64)

Thanks, @grantfirl!

Waiting for NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/311 being merged.

**Comment by zach1221** [comment]
atmos_cubed_sphere hash: https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/commit/6663459e58a04e3bda2157d5891d227e3abc3c7a

**Comment by zach1221** [comment]
@jkbk2004 We have approvals here, can you please merge this PR?
