### PR TITLE
Merge HAFS coupling related developments back into FV3atm develop

### LINKED ISSUE #709: Integrate HAFS HYCOM/WW3/CDEPS coupling related developments back into ufs-weather-model develop
## Description
Recently, with the great collaboration among NESII/EMC/DTC, the HAFS coupling related development reached a few major milestones, for which we think they can be merged/integrated back to the ufs-weather-model develop branch. More specifically, we have the following developments/enhancements ready for going back to ufs-weather-model develop branch:
- HAFS FV3ATM-HYCOM coupling, which is currently used in HAFSv0.2A/D HFIP real-time parallel experiments for 2021 hurricane season
- HAFS FV3ATM-WW3 coupling, for which technical testing has been conducted and the WW3 related changes have already been merged back to WW3's develop branch
- HAFS related CDEPS data component coupling development (with some CDEPS data component coupling regression tests added)
- HAFSv0.2 related physics enhancement specialized for the UFS-HAFS (hurricane) application (namelist controlled options added and does not affect other applications unless the related options are used)

## Solution
The developments are already available in the corresponding support/HAFS branches under the hafs-community forks. So, the solution is to merge/integrate the corresponding support/HAFS branches back to ufs-weather-model develop branch and its submodules.

## Alternatives
No actual alternatives unless we want to keep these HAFS-related developments isolated from the ufs-weather-model side, which we would definitely strive to avoid if possible.

## Related to
Issues:
- ncar/ccpp-physics/issues/683
- ncar/ccpp-physics/issues/700

PRs:
- ufs-community/ufs-weather-model/pull/715
- noaa-emc/fv3atm/pull/355
- noaa-gfdl/gfdl_atmos_cubed_sphere/pull/121
- ncar/ccpp-physics/pull/701
- noaa-emc/cmeps/pull/56
- noaa-emc/cdeps/pull/35

### PR DESCRIPTION
**Pull request by BinLiu-NOAA**
## Description
Merge HAFS HYCOM/WW3/CDEPS coupling related developments back into FV3atm develop.

A. More details about the HAFS coupling related changes (from @danrosen25)
- gfs_physics_nml namelist modification (inpunt.nml file)
  - added cpl_imp_mrg used in assign_importdata
  - added cpl_imp_dbg used in assign_importdata
- assign_importdata subroutine modification
  - added argument jdat, which is used to timestamp cpl_imp_dbg output
  - if cpl_imp_mrg then assign_importdata will compare import data to missing_value (9.99e20). If import data equals missing value and import field is 'sea_surface_temperature' then Sfcprop%tsfco is set to Sfcprop%tsfc instead of import data. merged data is then stored in datar8, which is a local copy of the import data.
  - if cpl_imp_dbg then the merged data stored in datar8 is written out to netcdf files
- realizeConnectedCplFields
  - added optional argument fill_value, which is used to fill completed ESMF_Field, defaults to 0.0
- fv3_cap
  - import data realized with 9.99e20 fill_value
- module_fcst_grid_comp
  - removed commented out code in regional grid creation
  - fixed grid alignment for regional fcstGrid
  - added corner coordinates (edges) to regional fcstGrid, using internal ATM%lon_bnd and ATM%lat_bnd
  - writes forecast grid to NetCDF if DumpFields = true in nems.configure

B. Added the following HAFS development related namelist options: cplice, rlmx, elmax, sfc_rlm (more details can be seen from ncar/ccpp-physics/pull/701)

C. Renamed and added HAFS related ccpp suites

### Issue(s) addressed
- fixes ufs-community/ufs-weather-model/issues/709
- fixes ncar/ccpp-physics/issues/683
- fixes ncar/ccpp-physics/issues/700

## Testing
The ufs-weather-model level standard regression tests passed on Orion after syncing with ufs-weather-model develop and its submodules as of 07/23/2021.

## Dependencies
- dependent on ncar/ccpp-physics/pull/701
- associated with ufs-community/ufs-weather-model/pull/715
- associated with noaa-emc/cmeps/pull/56
- associated with noaa-emc/cdeps/pull/35

## Contributors
NESII: @danrosen25, @uturuncoglu, @rsdunlapiv 
EMC: @BinLiu-NOAA, @ChunxiZhang-NOAA, @WeiguoWang-NOAA, @BijuThomas-NOAA, @JunghoonShin-NOAA, @ZhanZhang-NOAA and the whole EMC Hurricane Project team; @JessicaMeixner-NOAA and @aliabdolali from the EMC Wave Modeling team
AOML: @hyunsookkim-NOAA, @AndrewHazelton
DTC: @evankalina
and other UFS HAFS Application Team collaborators

### CODE REVIEW

File: atmos_model.F90 [hunk 1]
```diff
@@ -155,11 +155,13 @@ module atmos_model_mod
...
 logical :: debug        = .false.
 !logical :: debug        = .true.
+logical :: merge_import = .true.
+logical :: debug_merge  = .false.
 logical :: sync         = .false.
 integer, parameter     :: maxhr = 4096
 real, dimension(maxhr) :: fdiag = 0.
 real                   :: fhmax=384.0, fhmaxhf=120.0, fhout=3.0, fhouthf=1.0,avg_max_length=3600.
-namelist /atmos_model_nml/ blocksize, chksum_debug, dycore_only, debug, sync, fdiag, fhmax, fhmaxhf, fhout, fhouthf, ccpp_suite, avg_max_length
+namelist /atmos_model_nml/ blocksize, chksum_debug, dycore_only, debug, sync, fdiag, fhmax, fhmaxhf, fhout, fhouthf, ccpp_suite, avg_max_length, merge_import, debug_merge
```
Comment (junwang-noaa) [inline atmos_model.F90]: please remove fdiag, fhmax, fhmaxhf, fhout, fhouthf that were removed in PR#691. 
Also why do you need to merge_import variable in dycore atmosphere.F90

File: atmos_model.F90 [hunk 2]
```diff
@@ -1706,6 +1717,9 @@ subroutine assign_importdata(rc)
             call ESMF_FieldGet(importFields(n),farrayPtr=datar82d,localDE=0, rc=rc)
             if (ESMF_LogFoundError(rcToCheck=rc, msg=ESMF_LOGERR_PASSTHRU, line=__LINE__, file=__FILE__)) return
             datar8 = datar82d
+            if (merge_import) then
+              mergeflg(:,:) = datar82d(:,:).eq.missing_value
```
Comment (junwang-noaa) [inline atmos_model.F90:1698]: Will mergeflg need only be set up once?

File: fv3_cap.F90 [hunk 3]
```diff
@@ -222,6 +222,16 @@ subroutine InitializeAdvertise(gcomp, rc)
     write(msgString,'(A,l6)') trim(subname)//' cplprint_flag = ',cplprint_flag
     call ESMF_LogWrite(trim(msgString), ESMF_LOGMSG_INFO, rc=rc)
 
+    call ESMF_AttributeGet(gcomp, name="Diagnostic", value=value, defaultValue="0", &
```
Comment (junwang-noaa) [inline fv3_cap.F90]: What is this diagnostic variable used for? Do we need it for all the applications?

File: module_fcst_grid_comp.F90 [hunk 4]
```diff
@@ -560,6 +574,12 @@ subroutine fcst_initialize(fcst_comp, importState, exportState, clock, rc)
 !       if (ESMF_LogFoundError(rcToCheck=rc, msg=ESMF_LOGERR_PASSTHRU, line=__LINE__, file=__FILE__)) return
 !     endif
 !
+!test to write out netcdf file:
+        if (btest(diagnostic,16)) then
```
Comment (junwang-noaa) [inline module_fcst_grid_comp.F90]: What does this line do? Can we use a flag to control if we want to output the grid file?

File: atmos_model.F90 (hunk 1 above)
Comment (danrosen25) [reply atmos_model.F90]: I'm open to replacing or moving the merge_import configuration option but as long as it's part of the atmos_model_nml namelist it needs to be included anywhere the namelist is read.

File: atmos_model.F90 (hunk 2 above)
Comment (danrosen25) [reply atmos_model.F90:1698]: Missing values are cells outside the remapping/interpolation boundary. If configured properly then ESMF regridding will leave the indicator value of 9.99e20. If the domain ever moves then mergeflg needs to be calculated every time the domain moves (either at the source, internal to the atm, or the landsea mask changes). If variables ever use different domains then mergeflg needs to be computed for each variable. I'm open to other suggestions for merge_import and mergeflg. Also, if the application does not use CMEPS and the domain is changing then the import fields need to be reset to 9.99e20 each time the domain moves.

File: module_fcst_grid_comp.F90 (hunk 4 above)
Comment (danrosen25) [reply module_fcst_grid_comp.F90]: I use it to write out the regional grid information if bit 16 is set. The function, which I stored with io writes out a netcdf file with center coordinates, corner coordinates, mask, area computed by regridding (when needed), and area stored in grid. I don't know if this will be needed going forward but it help me diagnose the stagger alignment needed for the corners.

File: fv3_cap.F90 (hunk 3 above)
Comment (danrosen25) [reply fv3_cap.F90]: I pulled the Diagnostic value from the FV3 component attributes and store it for later use when I want to write out the grid information or not. I can remove the diagnostics that I added and used for developing the coupled regional grid. Feel free to make suggestions.

File: atmos_model.F90 (hunk 1 above)
Comment (BinLiu-NOAA) [reply atmos_model.F90]: @junwang-noaa, sure, I will remove fdiag, fhmax, fhmaxhf, fhout, fhouthf accordingly.
@danrosen25, in terms of the merge_import, debug_merge options, I was thinking of they can be moved the the same section as (cplflx, cplwav, etc.), since they are all coupling related. Another advantage is that, in this case, we will not need to make any changes to the GFDL_atmos_cubed_sphere dycore (thus this PR: NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/121 will no longer needed). 

BTW, probably can also consider renaming debug_merge into merge_debug. Thanks!

File: atmos_model.F90 (hunk 2 above)
Comment (BinLiu-NOAA) [reply atmos_model.F90:1698]: @danrosen25 and @junwang-noaa, there are moving-nesting capability under development, and in the future potentially we could couple the moving nesting grid with other model component.

File: module_fcst_grid_comp.F90 [hunk 5]
```diff
@@ -468,6 +470,18 @@ subroutine fcst_initialize(fcst_comp, importState, exportState, clock, rc)
...
+          glonPtr(tlb(1):tub(1),tlb(2):tub(2)) = &
+             atm_int_state%Atm%lon_bnd(tlb(1):tub(1),tlb(2):tub(2)) * dtor
+          call ESMF_GridGetCoord(fcstGrid, coordDim=2, staggerLoc=ESMF_STAGGERLOC_CORNER, &
+                                 totalLBound=tlb, totalUBound=tub, &
+                                 farrayPtr=glatPtr, rc=rc); ESMF_ERR_ABORT(rc)
+          glatPtr(tlb(1):tub(1),tlb(2):tub(2)) = &
+            atm_int_state%Atm%lat_bnd(tlb(1):tub(1),tlb(2):tub(2)) * dtor
           !call ESMF_GridAddCoord(fcstGrid, staggerLoc=ESMF_STAGGERLOC_CORNER, staggerAlign=(/1,1/), rc=rc); ESMF_ERR_ABORT(rc)
           !call ESMF_GridGetCoord(fcstGrid, coordDim=1, staggerLoc=ESMF_STAGGERLOC_CORNER,           farrayPtr=glonPtr, rc=rc); ESMF_ERR_ABORT(rc)
           !call ESMF_GridGetCoord(fcstGrid, coordDim=2, staggerLoc=ESMF_STAGGERLOC_CORNER,           farrayPtr=glatPtr, rc=rc); ESMF_ERR_ABORT(rc)
```
Comment (DusanJovic-NOAA) [inline module_fcst_grid_comp.F90]: Please remove these commented lines (485-494)

File: module_fcst_grid_comp.F90 (hunk 4 above)
Comment (DusanJovic-NOAA) [reply module_fcst_grid_comp.F90]: This is to cryptic, and non intuitive. Can't you use more descriptive name, like 'diagnose_grid_info' and make it logical variable. I do not see any advantage of using bit 16 in an integer to store information that user wants this debug file to be written out.
I know you can store up to 32 bits of information in a single variable, but that just makes configuration file less readable, documentation more complicated etc.

File: module_fv3_config.F90 [hunk 6]
```diff
@@ -28,5 +28,7 @@ module module_fv3_config
   character(esmf_maxstr),dimension(:),allocatable :: filename_base
   character(17)            :: calendar='                 '
   integer                  :: calendar_type = -99
+!
+  integer                  :: diagnostic = 0
```
Comment (DusanJovic-NOAA) [inline module_fv3_config.F90]: All variables in this module are read in from `model_configure` esmf config file, except `diagnostic` which is stored in fv3 component attributes. This is inconsistent.

File: atmos_model.F90 (hunk 1 above)
Comment (danrosen25) [reply atmos_model.F90]: @BinLiu-NOAA @junwang-noaa 
How about I move these configuration options into gfs_physics_nml and rename them `cpl_imp_mrg` and `cpl_imp_dbg`? They will be part of the GFS_control_type and can be referenced using Model%cpl_imp_mrg and Model%cpl_imp_dbg. They will both default to false. See the metadata below.

ccpp/data/GFS_typedefs.meta
```
[cpl_imp_mrg]
  standard_name = flag_for_merging_imported_data
  long_name = flag controlling cpl_imp_mrg for imported data (default off)
  units = flag
  dimensions = ()
  type = logical
[cpl_imp_dbg]
  standard_name = flag_for_debugging_merged_imported_data
  long_name = flag controlling cpl_imp_dbg for imported data (default off)
  units = flag
  dimensions = ()
  type = logical
```
ccpp/data/GFS_typedefs.F90
`NAMELIST /gfs_physics_nml/ `

File: module_fv3_config.F90 (hunk 6 above)
Comment (danrosen25) [reply module_fv3_config.F90]: Hi @DusanJovic-NOAA 
I took a look through the fv3_cap and found an existing diagnostic routine that I'd like to mimic the `diagnose_cplFields` subroutine. So basically I would move `subroutine write_grid_netcdf` from `io/module_write_netcdf.F90` to `cpl/module_cap_cpl.F90` and rename it as `subroutine diagnose_fcstGrid`. I can eliminate the newly added `diagnostic` integer and utilize the existing diagnostic configuration variables. At the end of the `InitializeRealize` I would add the following.
```
if( dbug > 0 .or. cplprint_flag ) then
  call diagnose_fcstGrid(fcstGrid, "diagnostic_FV3_fcstGrid.nc", regridArea=.TRUE., rc=rc)
  if (ESMF_LogFoundError(rcToCheck=rc, msg=ESMF_LOGERR_PASSTHRU, line=__LINE__, file=__FILE__)) return
endif
```
I like this strategy because it fully follows existing diagnostic code built into FV3. What do you think?

Comment (DusanJovic-NOAA) [reply module_fv3_config.F90]: Yes, I think `cpl/module_cap_cpl.F90` is better place for `diagnose_fcstGrid` than `io/module_write_netcdf.F90` since it is using ESMF's write routines, while the code in module_write_netcdf is using native netcdf calls.

File: atmos_model.F90 (hunk 1 above)
Comment (BinLiu-NOAA) [reply atmos_model.F90]: @danrosen25, this looks good to me. And with this, the NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/121 PR will no longer be needed). Thanks!

**Comment by junwang-noaa** [comment]
I think the proposed approach will make the code more consistent

File: atmos_model.F90 (hunk 1 above)
Comment (danrosen25) [reply atmos_model.F90]: @BinLiu-NOAA @junwang-noaa 
Okay, I'm going forward with the flags/descriptions as displayed below. I'm working on this now.
```
[cpl_imp_mrg]
  standard_name = flag_for_merging_imported_data
  long_name = flag controlling cpl_imp_mrg for imported data (default off)
  units = flag
  dimensions = ()
  type = logical
[cpl_imp_dbg]
  standard_name = flag_for_debugging_merged_imported_data
  long_name = flag controlling cpl_imp_dbg for imported data (default off)
  units = flag
  dimensions = ()
  type = logical
```

Comment (danrosen25) [reply atmos_model.F90]: This comment has been addressed in https://github.com/NOAA-EMC/fv3atm/pull/355/commits/6ac48b1d36b5559500dcb4718bae9140206fc2b8

File: fv3_cap.F90 (hunk 3 above)
Comment (danrosen25) [reply fv3_cap.F90]: This comment has been addressed in https://github.com/NOAA-EMC/fv3atm/pull/355/commits/6ac48b1d36b5559500dcb4718bae9140206fc2b8. Diagnostic was removed.

File: module_fcst_grid_comp.F90 (hunk 4 above)
Comment (danrosen25) [reply module_fcst_grid_comp.F90]: This comment has been addressed in https://github.com/NOAA-EMC/fv3atm/pull/355/commits/6ac48b1d36b5559500dcb4718bae9140206fc2b8
diagnostic was removed and grid write to netcdf now uses cplprint_flag

File: module_fcst_grid_comp.F90 (hunk 5 above)
Comment (danrosen25) [reply module_fcst_grid_comp.F90]: Removed.

File: module_fv3_config.F90 (hunk 6 above)
Comment (danrosen25) [reply module_fv3_config.F90]: This comment has been addressed in https://github.com/NOAA-EMC/fv3atm/pull/355/commits/6ac48b1d36b5559500dcb4718bae9140206fc2b8
I was unable to move the call into fv3_cap because the fcstGrid is created as a component of the module_fcst_grid_comp, which is a subset of the fv3_cap. I moved the subroutine out of io and into module_fcst_grid_comp and it is called using cplprint_flag (DumpFields)

**Review by junwang-noaa — APPROVED** [review]

**Review by DusanJovic-NOAA — APPROVED** [review]

File: ccpp/data/GFS_typedefs.meta [hunk 7]
```diff
@@ -2588,6 +2588,12 @@
   units = flag
   dimensions = ()
   type = logical
+[cplice]
```
Comment (climbfuji) [inline ccpp/data/GFS_typedefs.meta:2591]: We may have to update those new standard names in a follow-up PR, following the rules for standard names in https://github.com/ESCOMP/CCPPStandardNames. Not in this PR anymore, of course. @grantfirl @ligiabernardet FYI.

**Review by climbfuji — APPROVED** [review]
I merged ccpp-physics, the new hash in NCAR main is 4960c9a. I think you updated it already, while I was reviewing the code :-)
