### PR TITLE
Prate_avg fix (#979), UPP call freq and single restart var (#973) combo

### LINKED ISSUE #969: fix the output frequency for UPP when IAU is turned on
## Description
In GFSv17 IAU test, it is found that the UPP is called more frequently than it should be. This needs to be fixed.

### To Reproduce:
What compilers/machines are you seeing this with?
Give explicit steps to reproduce the behavior.
1. do this
2. then that
3. then, oops, look at the bug

## Additional context
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- needs to be fixed also in noaa-emc/nems/issues/<issue_number>
- needed for noaa-emc/fv3atm/pull/<pr_number>

## Output

**Screenshots**
If applicable, drag and drop screenshots to help explain your problem.

**output logs**
If applicable, include relevant output logs.
Either drag and drop the entire log file here (if a long log) or

```
paste the code here (if a short section of log)
```

## Testing:

1. Have you tested the code changes? On what platforms?

2. Have you run regression test in ufs-weather-model or ufs-s2s-model with code changes?
- Will the baseline results change? 
- If the baseline results change, is it expected? Please give brief explanation.

## Dependent PRs:

Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- required to support noaa-emc/GFDL_atmos_cubed_sphere/issues/<issue_number>
- ncar/ccpp-physics/pull/<pr_number>
- associated ufs-weather-model/pull/<pr_number>

### LINKED ISSUE #976: How is time averaged precipitation calculated?
I am confused how the time averaged precipitation calculated in the FV3. I know how precipitation is accumulated with time but don't have a clue how time averaging is done.

### LINKED ISSUE #978: using restart_fh for restart interval in fv3atm
## Description
This issue is related to the UFS weather model issue: https://github.com/ufs-community/ufs-weather-model/issues/2767. Currently there are two restart control variables, restart_fh for marine and restart_interval for ATM, because they are using different starting times for frequency. Work will be done in both marine components and fv3atm to use a single restart output time control variable and have consistent restart times during the integration w/wo IAU or restart from a certain forecast time.  

## Solution
Add a clear and concise description of what solution you provide.

## Alternatives
If applicable, add a description of any alternative solutions or features you've considered.

## Testing:

1. Have you tested the code changes? On what platforms?
2. Have you run regression test in ufs-weather-model or ufs-s2s-model with code changes?
- Will the baseline results change?
- If yes, please give brief explanation of your code updates on the regression test.

## Dependent PRs:

Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- required to support noaa-emc/GFDL_atmos_cubed_sphere/issues/<issue_number>
- ncar/ccpp-physics/pull/<pr_number>
- associated ufs-weather-model/pull/<pr_number>

### PR DESCRIPTION
**Pull request by dpsarmie**
## Description
This PR is combining #979 and part of #973. The fixes were originally developed by Jun Wang. This PR is just to combine these fixes and allow the changes to be added to the UFS PR queue.

----------
### #979 Fix zero accumulated total precip **(Changes in baselines)**
```
ccpp/CCPP_driver.F90
fv3/atmos_model.F90
fv3/fv3_cap.F90
```
This PR is to resolve the issue with https://github.com/NOAA-EMC/fv3atm/issues/976. The average total precipitation fields (accumulated from cycle starting time) are not correct in GFSv17 retro run.

The following code changes in production/GFS.16 were lost in the current fv3atm ccpp driver code: https://github.com/NOAA-EMC/fv3atm/blob/production/GFS.v16/gfsphysics/GFS_layer/GFS_driver.F90#L643-L649

```
  if (Model%iau_offset > 0) then
      kdt_iau = nint(Model%iau_offset*con_hr/Model%dtp)
      if (Model%kdt == kdt_iau+1) then
        iauwindow_center = .true.
        do nb = 1,nblks
          call Diag(nb)%rad_zero  (Model)
          call Diag(nb)%phys_zero (Model,iauwindow_center=iauwindow_center)
```
ccpp_driver.F90 is updated with the code.

----------
### #973 Fix upp calling frequency when restart freq is not equal to history file freq **(No baseline changes)** 
```
fv3/io/module_wrt_grid_comp.F90
```
This PR is to fix the upp calling frequency when the restart output frequency and history file output frequency are not same. One example is in cpld_control_gfsv17_iau test, where the restart frequency is 3 while the history output frequency is 6. The inline post should only be called at the history output frequency, even when history files are written out (controlled by output_history).

----------
### #973 Allow marine components and fv3atm to use a single restart output time control variable **(No baseline changes)**
```
fv3/module_fcst_grid_comp.F90
```
The marine and atm restart interval variables will now be based off of one variable. There will now be consistent restart times during the integration with and without IAU or restart from a certain forecast time.

----------
----------
### Issue(s) addressed

- Closes #976 
- Closes https://github.com/NOAA-EMC/GFS/issues/1
- Closes #969 
- Closes #978 

PRs:
- Closes #979 
- Closes #973 

## Testing

How were these changes tested?  **The UFS RT suite was run on Hercules**
Are the changes covered by regression tests? **Yes**  
Have the ufs-weather-model regression test been run? On what platform?   **The UFS RT suite was run on Hercules**
- Will the code updates change regression test baseline? **Yes, the precipitation averaging change does change baselines**

## Dependencies

If testing this branch requires non-default branches in other repositories, list them.

Do PRs in upstream repositories need to be merged first? **No**

### CODE REVIEW

**Comment by jkbk2004** [comment]
all tests are done ok at https://github.com/ufs-community/ufs-weather-model/pull/2836. this pr can be merged.

**Review by jkbk2004 — APPROVED** [review]

**Review by BrianCurtis-NOAA — APPROVED** [review]

File: fv3/fv3_cap.F90 [hunk 1]
```diff
@@ -1005,11 +1005,7 @@ subroutine OutputHours_FrequencyInput(nfhmax, output_startfh, outputfh2)
     if( nfhmax>output_startfh) nfh = nint((nfhmax-output_startfh)/outputfh2(1)) + 1
     if( nfh > 0) then
       allocate(output_fh(nfh))
-      if( output_startfh == 0) then
-        output_fh(1) = dt_atmos/3600.
-      else
-        output_fh(1) = output_startfh
-      endif
+      output_fh(1) = output_startfh + dt_atmos/3600.
```
Comment (NickSzapiro-NOAA) [inline fv3/fv3_cap.F90:1008]: I don't understand...why output at dt_atmos/3600. regardless of what was requested?

Comment (dpsarmie) [reply fv3/fv3_cap.F90:1008]: I think that was to make the IAU output at the first time step anyways to be consistent with the cold start methodology.
https://github.com/NOAA-EMC/fv3atm/pull/979#issuecomment-2996953085
