### PR TITLE
Make surface emissivity over water a persistent variable

### LINKED ISSUE #914: all zero values in atmImp_Faxa_lwnet over ocean for cpld_control_p7 test
## Description
`atmImp_Faxa_lwnet` variable in the mediator history output has all zero over the ocean. This is probably passed to the other model components such as MOM6 that could cause an issue.

### To Reproduce:
What compilers/machines are you seeing this with? Intel+MPT on Cheyenne
Give explicit steps to reproduce the behavior.
1. checkout ufs-wearher model (head of develop)
2. add mediator history phase to the run sequence in nems.configure (`MED med_phases_history_write`)
3. run model
4. check `atmImp_Faxa_lwnet` in the mediator history file.

## Output
Screen Shot 2021-11-16 at 9 55 36 AM

### PR DESCRIPTION
**Pull request by climbfuji**
## Description

The surface emissivity over water is currently stored in the `GFS_interstitial_type` DDT, which is not persistent. To fix the issues described in https://github.com/ufs-community/ufs-weather-model/issues/914, it needs to be moved to a persistent data type. This PR moves it to the `GFS_sfcprop_type`, which is already home to the surface emissivity over land and ice.

Note that in the long run, in case restart reproducibility is broken, `Sfcprop%emis_wat` might need to be added to the restart files. Right now it doesn't matter, because the emissivity over water is just a constant value that gets set again and again each time step.

### Issue(s) addressed

Fixes https://github.com/ufs-community/ufs-weather-model/issues/914

## Testing

See https://github.com/ufs-community/ufs-weather-model/pull/921

## Dependencies

- waiting on https://github.com/NCAR/ccpp-physics/pull/787

### CODE REVIEW

**Comment by climbfuji** [comment]
Adding @SMoorthi-emc only for his information later on, because he is on leave for the rest of the year.

File: io/module_wrt_grid_comp.F90 [hunk 1]
```diff
@@ -548,6 +548,28 @@ subroutine wrt_initialize(wrt_comp, imp_state_write, exp_state_write, clock, rc)
             latPtr(i,j) = lat(j)
```
Comment (DusanJovic-NOAA) [inline io/module_wrt_grid_comp.F90:548]: Not strictly part of this PR, but I would suggest instead of recomputing lonPtr(i,j) (line 547) to use already computed values from array lon (line 541). BTW, for consistency, the index in that loop (540-542) should be `i`, not `j`.

**Comment by climbfuji** [comment]
@DusanJovic-NOAA please check if https://github.com/NOAA-EMC/fv3atm/pull/434/commits/cb72fdae7eec367dbe836c4f5e03d149c6751f9c AND https://github.com/NOAA-EMC/fv3atm/pull/434/commits/91d48d7226ff3146e0b55ffcfe76dc3c7a7c8169 do what you suggested. Thanks!

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA please check if [cb72fda](https://github.com/NOAA-EMC/fv3atm/commit/cb72fdae7eec367dbe836c4f5e03d149c6751f9c) AND [91d48d7](https://github.com/NOAA-EMC/fv3atm/commit/91d48d7226ff3146e0b55ffcfe76dc3c7a7c8169) do what you suggested. Thanks!

Looks good to me.

**Review by DusanJovic-NOAA — APPROVED** [review]

**Review by junwang-noaa — APPROVED** [review]

**Comment by climbfuji** [comment]
Hash for ccpp-physics is correct, please merge.

**Review by DeniseWorthen — APPROVED** [review]
