### PR TITLE
Fix dumpfields=true option by using ESMF_FieldBundleWrite

### LINKED ISSUE #1765: dumpfields=true fails in module_fcst_grid_comp.F90 for coupled model
## Description

The nems.configure variable ``dumpfields=true`` should allow the coupling fields to be written from the component itself. This feature was previously working in the fv3_cap, but now fails with the following error:

```
20230522 132033.780 ERROR            PET000 ESMCI_IO.C:542 ESMCI::IO::write() Operation not yet supported  - tile count of 6 != 1 - not supported yet
20230522 132033.791 ERROR            PET000 ESMCI_IO.C:942 ESMCI::IO::close() Unable to close file  - Internal subroutine call returned Error
20230522 132033.791 ERROR            PET000 ESMCI_IO.C:482 ESMCI::IO::write() Operation not yet supported  - Internal subroutine call returned Error
20230522 132033.791 ERROR            PET000 ESMCI_ArrayBundle.C:493 ESMCI::ArrayBundle::write() Unable to write to file  - Internal subroutine call returned Error
20230522 132033.791 ERROR            PET000 ESMCI_ArrayBundle_F.C:436 c_esmc_arraybundlewrite() Unable to write to file  - Internal subroutine call returned Error
20230522 132033.791 ERROR            PET000 ESMF_ArrayBundle.F90:3976 ESMF_ArrayBundleWrite() Unable to write to file  - Internal subroutine call returned Error
20230522 132033.791 ERROR            PET000 module_fcst_grid_comp.F90:1638 Unable to write to file  - Passing error in return code
20230522 132033.791 ERROR            PET000 module_fcst_grid_comp.F90:298 Unable to write to file  - Passing error in return code
20230522 132033.791 ERROR            PET000 module_fcst_grid_comp.F90:865 Unable to write to file  - Passing error in return code
20230522 132033.791 ERROR            PET000 fv3_cap.F90:396 Unable to write to file  - Passing error in return code
20230522 132033.791 ERROR            PET000 ATM:src/addon/NUOPC/src/NUOPC_ModelBase.F90:700 Unable to write to file  - Passing error in return code
20230522 132033.791 ERROR            PET000 UFS Driver Grid Comp:src/addon/NUOPC/src/NUOPC_Driver.F90:2577 Unable to write to file  - Phase 'IPDvXp01' Initialize for modelComp 2: ATM did not return ESMF_SUCCESS
20230522 132033.791 ERROR            PET000 UFS Driver Grid Comp:src/addon/NUOPC/src/NUOPC_Driver.F90:1286 Unable to write to file  - Passing error in return code
20230522 132033.792 ERROR            PET000 UFS Driver Grid Comp:src/addon/NUOPC/src/NUOPC_Driver.F90:457 Unable to write to file  - Passing error in return code
20230522 132033.792 ERROR            PET000 UFS.F90:386 Unable to write to file  - Aborting UFS
```

CMEPS has the capability in the mediator history files to write the fields it receives but it is sometimes useful to confirm that the fields imported by CMEPS are identical to those exported by FV3. This is no longer possible. 

### To Reproduce:

Run any of the global coupled configurations using the RT system. Use the run directory and set ``DumpFields = true`` in the ATM configuration attributes in ``nems.configure``.

### PR DESCRIPTION
**Pull request by DusanJovic-NOAA**
## Description

This PR fixes `dumpfields=true` option which can be used to write all coupling fields (from import and export states) by using updated version of ESMF's `ESMF_FieldBundleWrite` function instead of old `ESMFIO_Write`.

Fixes https://github.com/ufs-community/ufs-weather-model/issues/1765

Is a change of answers expected from this PR?  No.

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues should always be created before starting work on a PR branch!)
- fixes https://github.com/ufs-community/ufs-weather-model/issues/1765

## Testing

How were these changes tested?  
What compilers / HPCs was it tested with?  
Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)  
Have the ufs-weather-model regression test been run? On what platform?  
- Will the code updates change regression test baseline? If yes, why? Please show the baseline directory below.
- Please commit the regression test log files in your ufs-weather-model branch

## Dependencies

N/A

### CODE REVIEW

**Comment by DusanJovic-NOAA** [comment]
When I run one of the coupled regression tests (cpld_control_p8_intel) with `DumpFields = true` I see this error in PET000 file:
```
20240703 150754.552 ERROR            PET000 ESMCI_IO.C:1614 ESMCI::IO::checkNtiles() Wrong data value  - New number of tiles (6) does not match previously-set number of tiles (1) for this IO object. All arrays handled by a given IO object must have the same number of tiles.
20240703 150754.554 ERROR            PET000 ESMCI_IO.C:1566 ESMCI::IO::setOrCheckNtiles() Wrong data value  - Internal subroutine call returned Error
20240703 150754.554 ERROR            PET000 ESMCI_IO.C:1064 ESMCI::IO::addArray() Wrong data value  - Internal subroutine call returned Error
20240703 150754.554 ERROR            PET000 /scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/cache/build_stage/spack-stage-esmf-8.6.0-nnuwc5zlpvogeiuk3nec26eryjiwsopw/spack-src/src/Infrastructure/Field/interface/ESMCI_Field_F.C:144 c_esmc_fieldioaddarray() Wrong data value  - Internal subroutine call returned Error
20240703 150754.554 ERROR            PET000 ESMF_FieldBundle.F90:17926 ESMF_FieldBundleWrite() Wrong data value  - Internal subroutine call returned Error
20240703 150754.554 ERROR            PET000 module_cap_cpl.F90:233 Wrong data value  - Passing error in return code
20240703 150754.554 ERROR            PET000 module_cap_cpl.F90:73 Wrong data value  - Passing error in return code
```
but model continues to execute.

I see only `fv3_cap_import_2021-03-22T06:00:00.tile?.nc` being created, but no `fv3_cap_export_...`. Probably due to an above error.

File: cpl/module_cap_cpl.F90 [hunk 1]
```diff
@@ -80,28 +79,36 @@ end subroutine diagnose_cplFields
...
+      integer, allocatable                   :: fieldDimLen(:)
+      character(len=32), allocatable         :: gridded_dim_labels(:), ungridded_dim_labels(:)
 
-      character(len=*),parameter :: subname='(module_cap_cpl:State_RWFields_tiles)'
+      character(16), parameter :: convention = 'NetCDF'
+      character(16), parameter :: purpose = 'FV3'
 
-      ! local variables
+      integer, parameter :: max_n_axes = 4
+      integer, parameter :: max_n_dim = 16
```
Comment (junwang-noaa) [inline cpl/module_cap_cpl.F90:111]: May I ask what the two variables mean? max_n_axes is 4 because it covers (x,y,z,time)? what about max_n_dim? is it all the possible dimensions used in the output file?

**Comment by junwang-noaa** [comment]
@DusanJovic-NOAA would you like to include the one line change in PR#857? That PR should have no impact on RT. Thanks

File: cpl/module_cap_cpl.F90 (hunk 1 above)
Comment (DusanJovic-NOAA) [reply cpl/module_cap_cpl.F90:111]: Yes. The max_n_dim is number possible dimensions labels for a given rank (1-4) where each label has different count.. This is typically needed for "ungridded  dimensions" like 'zaxis', when we can have different element counts for different fields, like 127, 128, (for model level data) and 4 and/or 9 for soil fields. Local array axes_dimcount is used to map axes id (1,2,3 or 4) and count to the id of an dimension that has the same count, which is then used to create ESMF_ATT_GRIDDED_DIM_LABELS  and ESMF_ATT_UNGRIDDED_DIM_LABELS attributes.

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA would you like to include the one line change in PR#857? That PR should have no impact on RT. Thanks

Sure, I can merge changes from #857.

**Comment by DeniseWorthen** [comment]
@DusanJovic-NOAA I'd like to add the fix the scalar_id=0 issue (#838). It also adds a check to enforce the setting of the NTile scalar index. I made a draft PR to your FV3 branch [here](https://github.com/DusanJovic-NOAA/fv3atm/pull/6).

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA I'd like to add the fix the scalar_id=0 issue (#838). It also adds a check to enforce the setting of the NTile scalar index. I made a draft PR to your FV3 branch [here](https://github.com/DusanJovic-NOAA/fv3atm/pull/6).

I just synced my branch with develop, can you sync your branch. Thanks.

**Comment by DeniseWorthen** [comment]
I should be up to date w/ develop.

**Comment by DeniseWorthen** [comment]
@DusanJovic-NOAA I've tested the dumpfields and it is working, but I've made a PR to your branch for a couple of changes. First, to add a timeslice, so that files can be ncrcat'td into a timeseries. Also, in the other components, we generally retrieve the ``OverwriteSlice`` config variable, which is always .true.. Since FV3 doesn't retrieve this right now, I just manually set the value as true.

The second change is to write the filenames w/ either an import time or export time string. This makes comparing w/ the mediator history files easier. I've checked that using the FV3 dump fields capability does match the mediator history files (matching cmeps 'import from atm' == fv3 'export from cap').

**Review by DeniseWorthen — APPROVED** [review]

**Comment by DeniseWorthen** [comment]
Thanks for fixing this @DusanJovic-NOAA. It has been not working for over a year!

**Review by junwang-noaa — APPROVED** [review]

**Comment by FernandoAndrade-NOAA** [comment]
Testing on #[2355](https://github.com/ufs-community/ufs-weather-model/pull/2355) has completed, please continue with the merge process here. Thank you.
